config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/become-a-practitioner', to: 'pages#become_a_practitioner', as: :become_a_practitioner

  get '/aboutus', to: 'pages#aboutus', as: :aboutus

  get '/faq', to: 'pages#faq', as: :faq

  get '/terms', to: 'pages#terms', as: :terms

  get '/privacy', to: 'pages#privacy', as: :privacy

  get '/cookie', to: 'pages#cookie', as: :cookie

  get '/practitioners/filter', to: 'practitioners#filter', as: :practitioner_filter

  get '/specialties/filter', to: 'specialties#filter', as: :specialty_filter

  get '/session/promo_code', to: 'sessions#promo_code', as: :session_promo_code

  get '/services/more', to: 'services#more'

  get '/user/timezone', to: 'users#timezone', as: :user_timezone

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  resources :users, only: [:show] do
    resources :practitioners, only: %i[new create]
    resources :conversations, only: [:create]
    resources :user_health_goals, only: [:create]
    resources :referred_users, only: [:create]
    resources :payment_methods, only: [:create]
    resources :user_promos, only: [:create]
  end

  resources :payment_methods, only: %i[update destroy]

  get '/payment', to: 'payments#payment', as: :user_payment

  get '/sessions', to: 'users#booking', as: :user_sessions
  get '/practitioner_sessions', to: 'practitioners#booking', as: :practitioner_sessions
  get '/favourites', to: 'users#favorite', as: :user_favorites
  get '/notifications', to: 'users#notification', as: :user_notifications

  resources :practitioners, only: %i[index show update destroy] do
    resources :practitioner_specialties, only: [:create]
    resources :practitioner_languages, only: [:create]
    resources :practitioner_social_links, only: [:create]
    resources :practitioner_certifications, only: [:create]
    resources :practitioner_memberships, only: [:create]
    resources :favorite_practitioners, only: [:create]
    resources :working_hours, only: [:create]
    resources :practitioner_payments, only: [:new]
  end

  get '/profile', to: 'practitioners#profile', as: :practitioner_profile
  get '/my_services', to: 'practitioners#service', as: :practitioner_services
  get '/discovery_call/:id', to: 'practitioners#discovery_call', as: :practitioner_discovery_call

  resources :practitioner_specialties, only: [:destroy]

  resources :practitioner_languages, only: [:destroy]

  resources :practitioner_social_links, only: [:destroy]

  resources :practitioner_certifications, only: [:destroy]

  resources :practitioner_memberships, only: [:destroy]

  resources :user_health_goals, only: [:destroy]

  resources :favorite_practitioners, only: [:destroy]

  resources :working_hours, only: %i[update destroy]

  resources :languages, only: %i[create destroy]

  resources :specialty_categories, only: %i[create destroy]

  resources :specialties, only: %i[show create destroy]

  resources :health_goals, only: %i[create destroy]

  resources :services, only: %i[create index show update destroy] do
    resources :sessions, only: [:create]
    resources :favorite_services, only: [:create]
    resources :service_health_goals, only: [:create]
    resources :service_promotions, only: [:create]
  end

  resources :service_promotions, only: %i[update destroy]

  resources :service_health_goals, only: [:destroy]

  resources :favorite_services, only: [:destroy]

  resources :sessions, only: %i[show edit update destroy] do
    resources :payments, only: [:new]
    resources :reviews, only: [:create]
  end

  resources :reviews, only: [:destroy]

  resources :notifications, only: %i[update destroy]

  resources :conversations, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :needs, only: [:show]

  resources :events, only: %i[index create show update destroy] do
    resources :event_attendees, only: [:create]
    resources :event_codes, only: [:create]
  end

  resources :event_attendees, only: [:destroy] do
    resources :event_attendee_payments, only: [:new]
  end

  resources :event_codes, only: [:destroy]

  get '/events/:id/codes', to: 'events#codes', as: :event_codes

  post '/events/:id/publish_codes', to: 'events#publish_codes', as: :event_publish_codes

  resources :tax_rates, only: %i[create update destroy]

  get '/blog', to: 'posts#index', as: :posts

  get '/blog/:id', to: 'posts#show', as: :post

  post '/blog', to: 'posts#create'

  get '/blog/:id/edit', to: 'posts#edit', as: :edit_post

  patch '/blog/:id', to: 'posts#update'

  put '/blog/:id', to: 'posts#update'

  delete '/blog/:id', to: 'posts#destroy'

  resources :posts, only: [:new]

  resources :post_categories, only: [:show]

  resources :post_sub_categories, only: [:show]

  resources :post_authors, only: [:show]

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # post '/background_check/modo_webhooks', to: 'background_check#modo_webhooks'

  post '/background_check/certn_webhooks', to: 'background_check#certn_webhooks'
end

app/models/practitioner_certification.rb
class PractitionerCertification < ApplicationRecord
  belongs_to :practitioner
  validates :certification_type, presence: true
  $certification_types = ['Education', 'Certification']
end

app/controllers/practitioner_certifications_controller.rb
class PractitionerCertificationsController < ApplicationController
  before_action :set_practitioner_certification, only: [:destroy]

  def create
    @practitioner_certification = PractitionerCertification.new(practitioner_certification_params)
    authorize @practitioner_certification
    @practitioner = Practitioner.find(params[:practitioner_id].split('_').last.to_i)
    @practitioner_certification.practitioner = @practitioner
    if @practitioner_certification.save!
      respond_to do |format|
        format.html { redirect_to practitioner_profile_path }
        format.js
      end
    end
  end

  def destroy
    @practitioner = @practitioner_certification.practitioner
    @practitioner_certification.destroy
    respond_to do |format|
      format.html { redirect_to practitioner_profile_path }
      format.js
    end
  end

  private

  def set_practitioner_certification
    @practitioner_certification = PractitionerCertification.find(params[:id])
    authorize @practitioner_certification
  end

  def practitioner_certification_params
    params.require(:practitioner_certification).permit(:certification_type, :name)
  end
end

app/helpers/practitioner_certifications_helper.rb
module PractitionerCertificationsHelper
end

app/views/practitioner_certifications/_practitioner_certifications_list.html.erb
<% if practitioner.practitioner_certifications.where(certification_type: 'Education').count > 0 %>
  <p><strong>Education</strong></p>
  <% practitioner.practitioner_certifications.where(certification_type: 'Education').each do |certification| %>
    <div class="practitioner-certification mb-2" data-certification-id="<%= certification.id %>">
      <div class="d-flex align-items-center">
        <p><%= certification.name %></p>
        <button data-toggle="tooltip" data-placement="bottom" data-original-title="Delete"><p><%= link_to '', practitioner_certification_path(certification), remote: true, method: :delete, data: { confirm: "Are you sure to remove this certification?"}, class: 'fas fa-trash' %></p></button>
      </div>
    </div>
  <% end %>
<% end %>
<% if practitioner.practitioner_certifications.where(certification_type: 'Certification').count > 0 %>
  <p><strong>Certification</strong></p>
  <% practitioner.practitioner_certifications.where(certification_type: 'Certification').each do |certification| %>
    <div class="practitioner-certification mb-2" data-certification-id="<%= certification.id %>">
      <div class="d-flex align-items-center">
        <p><%= certification.name %></p>
        <button data-toggle="tooltip" data-placement="bottom" data-original-title="Delete"><p><%= link_to '', practitioner_certification_path(certification), remote: true, method: :delete, data: { confirm: "Are you sure to remove this certification?"}, class: 'fas fa-trash' %></p></button>
      </div>
    </div>
  <% end %>
<% end %>

app/views/practitioner_certifications/create.js.erb
$("#certifications-list").html('<%= j render "practitioner_certifications_list", practitioner: @practitioner %>');
$("#progress").html('<%= j render  "practitioners/profile_progress_bar", practitioner: @practitioner %>');
certificationsForm.style.display = 'none';
certificationsForm.reset();
certificationsEdit.style.display = 'block';
<% if @practitioner_certification.errors.empty? %>
  <% flash[:notice] = "#{@practitioner_certification.certification_type} has been added." %>
  $("#flashes").html('<%= j render partial: "shared/flashes", locals: { notice: flash[:notice] } %>');
<% else %>
  $("#flashes").html('<%= j render partial: "shared/flashes", locals: { alert: flash[:alert] } %>');
<% end %>
$(function() {
  setTimeout(function(){
    $('.alert').slideUp(500);
  }, 2000);
});
if (document.querySelector('.tooltip')) {
  document.querySelector('.tooltip').remove();
}

app/views/practitioner_certifications/destroy.js.erb
$("#certifications-list").html('<%= j render "practitioner_certifications_list", practitioner: @practitioner %>');
$("#progress").html('<%= j render  "practitioners/profile_progress_bar", practitioner: @practitioner %>');
<% if @practitioner_certification.errors.empty? %>
  <% flash[:notice] = "#{@practitioner_certification.certification_type} has been deleted." %>
  $("#flashes").html('<%= j render partial: "shared/flashes", locals: { notice: flash[:notice] } %>');
<% else %>
  $("#flashes").html('<%= j render partial: "shared/flashes", locals: { alert: flash[:alert] } %>');
<% end %>
$(function() {
  setTimeout(function(){
    $('.alert').slideUp(500);
  }, 2000);
});
if (document.querySelector('.tooltip')) {
  document.querySelector('.tooltip').remove();
}