config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/become-a-practitioner', to: 'pages#become_a_practitioner', as: :become_a_practitioner

  get '/aboutus', to: 'pages#aboutus', as: :aboutus

  get '/faq', to: 'pages#faq', as: :faq

  get '/terms', to: 'pages#terms', as: :terms

  get '/privacy', to: 'pages#privacy', as: :privacy

  get '/cookie', to: 'pages#cookie', as: :cookie

  get '/practitioners/filter', to: 'practitioners#filter', as: :practitioner_filter

  get '/specialties/filter', to: 'specialties#filter', as: :specialty_filter

  get '/session/promo_code', to: 'sessions#promo_code', as: :session_promo_code

  get '/services/more', to: 'services#more'

  get '/user/timezone', to: 'users#timezone', as: :user_timezone

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  resources :users, only: [:show] do
    resources :practitioners, only: %i[new create]
    resources :conversations, only: [:create]
    resources :user_health_goals, only: [:create]
    resources :referred_users, only: [:create]
    resources :payment_methods, only: [:create]
    resources :user_promos, only: [:create]
  end

  resources :payment_methods, only: %i[update destroy]

  get '/payment', to: 'payments#payment', as: :user_payment

  get '/sessions', to: 'users#booking', as: :user_sessions
  get '/practitioner_sessions', to: 'practitioners#booking', as: :practitioner_sessions
  get '/favourites', to: 'users#favorite', as: :user_favorites
  get '/notifications', to: 'users#notification', as: :user_notifications

  resources :practitioners, only: %i[index show update destroy] do
    resources :practitioner_specialties, only: [:create]
    resources :practitioner_languages, only: [:create]
    resources :practitioner_social_links, only: [:create]
    resources :practitioner_certifications, only: [:create]
    resources :practitioner_memberships, only: [:create]
    resources :favorite_practitioners, only: [:create]
    resources :working_hours, only: [:create]
    resources :practitioner_payments, only: [:new]
  end

  get '/profile', to: 'practitioners#profile', as: :practitioner_profile
  get '/my_services', to: 'practitioners#service', as: :practitioner_services
  get '/discovery_call/:id', to: 'practitioners#discovery_call', as: :practitioner_discovery_call

  resources :practitioner_specialties, only: [:destroy]

  resources :practitioner_languages, only: [:destroy]

  resources :practitioner_social_links, only: [:destroy]

  resources :practitioner_certifications, only: [:destroy]

  resources :practitioner_memberships, only: [:destroy]

  resources :user_health_goals, only: [:destroy]

  resources :favorite_practitioners, only: [:destroy]

  resources :working_hours, only: %i[update destroy]

  resources :languages, only: %i[create destroy]

  resources :specialty_categories, only: %i[create destroy]

  resources :specialties, only: %i[show create destroy]

  resources :health_goals, only: %i[create destroy]

  resources :services, only: %i[create index show update destroy] do
    resources :sessions, only: [:create]
    resources :favorite_services, only: [:create]
    resources :service_health_goals, only: [:create]
    resources :service_promotions, only: [:create]
  end

  resources :service_promotions, only: %i[update destroy]

  resources :service_health_goals, only: [:destroy]

  resources :favorite_services, only: [:destroy]

  resources :sessions, only: %i[show edit update destroy] do
    resources :payments, only: [:new]
    resources :reviews, only: [:create]
  end

  resources :reviews, only: [:destroy]

  resources :notifications, only: %i[update destroy]

  resources :conversations, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :needs, only: [:show]

  resources :events, only: %i[index create show update destroy] do
    resources :event_attendees, only: [:create]
    resources :event_codes, only: [:create]
  end

  resources :event_attendees, only: [:destroy] do
    resources :event_attendee_payments, only: [:new]
  end

  resources :event_codes, only: [:destroy]

  get '/events/:id/codes', to: 'events#codes', as: :event_codes

  post '/events/:id/publish_codes', to: 'events#publish_codes', as: :event_publish_codes

  resources :tax_rates, only: %i[create update destroy]

  get '/blog', to: 'posts#index', as: :posts

  get '/blog/:id', to: 'posts#show', as: :post

  post '/blog', to: 'posts#create'

  get '/blog/:id/edit', to: 'posts#edit', as: :edit_post

  patch '/blog/:id', to: 'posts#update'

  put '/blog/:id', to: 'posts#update'

  delete '/blog/:id', to: 'posts#destroy'

  resources :posts, only: [:new]

  resources :post_categories, only: [:show]

  resources :post_sub_categories, only: [:show]

  resources :post_authors, only: [:show]

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # post '/background_check/modo_webhooks', to: 'background_check#modo_webhooks'

  post '/background_check/certn_webhooks', to: 'background_check#certn_webhooks'
end

app/models/need.rb
class Need < ApplicationRecord
  has_many :need_services, dependent: :destroy
  has_one_attached :photo
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_need, only: [:show]
  before_action :set_notifications, only: [:show]

  def show
    @need_services = @need.need_services
  end

  private

  def set_need
    @need = Need.find(params[:id])
    authorize @need
  end

  def set_notifications
    @notifications = Notification.includes(:actor).where(recipient: current_user).order('created_at DESC').unread
  end
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/views/needs/show.html.erb
<div class="container needs-page">
  <div class="needs-header">
    <div class="needs-img">
      <% if @need.photo.attached? %>
        <%= image_tag @need.photo %>
      <% else %>
        <%= image_tag("needs/#{@need.name.downcase}") %>
      <% end %>
    </div>
    <h2 class="text-center"><%= @need.name %></h2>
    <p class="needs-description"><%= @need.description.gsub(/\n/, '<br/>').html_safe %></p>
  </div>
  <div class="service-lists">
    <% @need_services.each do |service| %>
      <% if user_signed_in? %>
        <div class="service-list-item" data-matching="<%= service.service.matching_counts(current_user.health_goals.ids) %>">
      <% else %>
        <div class="service-list-item" data-matching="">
      <% end %>
        <div class="service-list-item-title details-desktop">
          <div class="d-flex">
            <div class="service-type">
              <p><%= service.service.service_type.capitalize %></p>
            </div>
            <h3>
              <%= link_to service.service.name, service_path(service.service) %>
            </h3>
            <% if service.service.service_promotions.exists? && service.service.active_promotion? %>
              <div class="d-flex" style="flex: 1 0 20%;">
                <div class="promo-rectangle">
                  <%= service.service.last_promotion.discount_percentage %>% off
                </div>
                <div class="promo-triangle"></div>
                <p class="small" style="color: red; margin-top: 0.125rem;">
                  <% if (service.service.last_promotion.end_date.to_date - Time.now.to_date).to_i > 1 %>
                    (<%= (service.service.last_promotion.end_date.to_date - Time.now.to_date).to_i %> days left)
                  <% elsif ((service.service.last_promotion.end_date.to_time - Time.now.to_time) / 1.hours).to_i > 1 %>
                    (<%= ((service.service.last_promotion.end_date.to_time - Time.now.to_time) / 1.hours).to_i  %> hours left)
                  <% else %>
                    (<%= ((service.service.last_promotion.end_date.to_time - Time.now.to_time) / 1.minutes).to_i  %> minutes left)
                  <% end %>
                </p>
              </div>
            <% end %>
          </div>
          <div class="fav-btn" id="fav-btn-<%= service.service.id %>">
            <% if user_signed_in? %>
              <%= render 'favorite_services/service_btn', service: service %>
            <% end %>
          </div>
        </div>
        <div class="service-list-item-title m-0 details-mobile-flex">
          <div class="service-type">
            <p class="m-0"><%= service.service.service_type.capitalize %></p>
          </div>
          <% if service.service.service_promotions.exists? && service.service.active_promotion? %>
            <div class="d-flex" style="flex: 1 0 20%;">
              <div class="promo-rectangle">
                <%= service.service.last_promotion.discount_percentage %>% off
              </div>
              <div class="promo-triangle"></div>
              <p class="small" style="color: red; margin-top: 0.125rem;">
                <% if (service.service.last_promotion.end_date.to_date - Time.now.to_date).to_i > 1 %>
                  (<%= (service.service.last_promotion.end_date.to_date - Time.now.to_date).to_i %> days left)
                <% elsif ((service.service.last_promotion.end_date.to_time - Time.now.to_time) / 1.hours).to_i > 1 %>
                  (<%= ((service.service.last_promotion.end_date.to_time - Time.now.to_time) / 1.hours).to_i  %> hours left)
                <% else %>
                  (<%= ((service.service.last_promotion.end_date.to_time - Time.now.to_time) / 1.minutes).to_i  %> minutes left)
                <% end %>
              </p>
            </div>
          <% end %>
          <div class="fav-btn" id="fav-btn-<%= service.service.id %>">
            <% if user_signed_in? %>
              <%= render 'favorite_services/service_btn', service: service %>
            <% end %>
          </div>
        </div>
        <div class="details-mobile">
          <h3>
            <%= link_to service.service.name, service_path(service.service) %>
          </h3>
        </div>
        <div class="service-list-item-body details-desktop">
          <div class="service-left-column">
            <div class="service-list-item-practitioner">
              <div class="profile-photo">
                <a href="/practitioners/<%= service.service.practitioner.user.full_name.delete(' ') %>_<%= service.service.practitioner.id %>">
                  <% if service.service.practitioner.user.photo.attached? %>
                    <img src="<%= cdn_for(service.service.practitioner.user.cropped_image) %>" class="service-list-item-user avatar-bordered mb-3" alt="">
                  <% else %>
                    <%= image_tag("profile", class: "service-list-item-user avatar-bordered mb-3") %>
                  <% end %>
                </a>
                <h6><%= link_to service.service.practitioner.user.full_name, practitioner_path(service.service.practitioner) %></h6>
                <p><%= service.service.practitioner.title %></p>
                <p><%= service.service.practitioner.location %></p>
              </div>
            </div>
          </div>
          <div class="service-middle-column">
            <div class="service-list-item-infos">
              <p id="service-description-<%= service.service.id %>"><%= service.service.description.gsub(/\n/, '<br/>').html_safe %></p>
            </div>
            <div class="service-list-item-goals mt-2">
              <% if user_signed_in? %>
                <% service.service.health_goals.order(:name).each do |goal| %>
                  <% if current_user.health_goals.include?(goal) %>
                    <div class="service-goal match"><%= goal.name %></div>
                  <% end %>
                <% end %>
                <% service.service.health_goals.order(:name).each do |goal| %>
                  <% unless current_user.health_goals.include?(goal) %>
                    <div class="service-goal"><%= goal.name %></div>
                  <% end %>
                <% end %>
              <% else %>
                <% service.service.health_goals.order(:name).each do |goal| %>
                  <div class="service-goal"><%= goal.name %></div>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="service-right-column">
            <div class="d-flex justify-content-between">
              <div style="flex: 0 0 45%;">
                <label>PRICE</label>
                <% if service.service.service_promotions.exists? && service.service.active_promotion? %>
                  <p style="color: red; font-weight: 600;">CA$ <%= number_with_precision((service.service.price - (service.service.price * service.service.last_promotion.discount_percentage / 100)), precision: 2, delimiter: ',') %></p>
                <% else %>
                  <p>CA$ <%= number_with_precision(service.service.price, precision: 2, delimiter: ',') %></p>
                <% end %>
              </div>
              <div style="flex: 0 0 45%;">
                <label>DURATION</label>
                <p><%= service.service.duration %> mins</p>
              </div>
            </div>
            <div class="d-flex justify-content-between">
              <div style="flex: 0 0 45%;">
                <label>SPECIALTY</label>
                <p><%= service.service.specialty.name %></p>
              </div>
              <div style="flex: 0 0 45%;">
                <label>Rating</label>
                <% if service.service.reviews.count > 0 %>
                  <p><i class="fas fa-star mr-2 pink-icon"></i><%= service.service.rating_avg %> (<%= service.service.reviews.count %>)</p>
                <% end %>
              </div>
            </div>
            <% if service.service.practitioner.user != current_user %>
              <div class="text-center mt-3">
                <a class="btn btn-flat" href="/services/<%= service.service.id %>">Details</a>
              </div>
            <% end %>
          </div>
        </div>
        <div class="service-list-item-body details-mobile">
          <div class="service-list-item-goals">
            <% if user_signed_in? %>
              <% service.service.health_goals.order(:name).each do |goal| %>
                <% if current_user.health_goals.include?(goal) %>
                  <div class="service-goal match"><%= goal.name %></div>
                <% end %>
              <% end %>
              <% service.service.health_goals.order(:name).each do |goal| %>
                <% unless current_user.health_goals.include?(goal) %>
                  <div class="service-goal"><%= goal.name %></div>
                <% end %>
              <% end %>
            <% else %>
              <% service.service.health_goals.order(:name).each do |goal| %>
                <div class="service-goal"><%= goal.name %></div>
              <% end %>
            <% end %>
          </div>
          <div class="service-list-item-practitioner">
            <div class="profile-photo">
              <a href="/practitioners/<%= service.service.practitioner.user.full_name.delete(' ') %>_<%= service.service.practitioner.id %>">
                <% if service.service.practitioner.user.photo.attached? %>
                  <img src="<%= cdn_for(service.service.practitioner.user.cropped_image) %>" class="service-list-item-user avatar-bordered mb-3" alt="">
                <% else %>
                  <%= image_tag("profile", class: "service-list-item-user avatar-bordered mb-3") %>
                <% end %>
              </a>
              <h6><%= link_to service.service.practitioner.user.full_name, practitioner_path(service.service.practitioner) %></h6>
            </div>
          </div>
          <div class="service-list-item-infos">
            <p id="service-description-mobile-<%= service.service.id %>"><%= service.service.description.gsub(/\n/, '<br/>').html_safe %></p>
          </div>
          <div class="d-flex justify-content-between mt-2">
            <div style="flex: 0 0 45%;">
              <label>PRICE</label>
              <% if service.service.service_promotions.exists? && service.service.active_promotion? %>
                <p style="color: red; font-weight: 600;">CA$ <%= number_with_precision((service.service.price - (service.service.price * service.service.last_promotion.discount_percentage / 100)), precision: 2, delimiter: ',') %></p>
              <% else %>
                <p>CA$ <%= number_with_precision(service.service.price, precision: 2, delimiter: ',') %></p>
              <% end %>
            </div>
            <div style="flex: 0 0 45%;">
              <label>DURATION</label>
              <p><%= service.service.duration %> mins</p>
            </div>
          </div>
          <% if service.service.practitioner.user != current_user %>
            <div class="text-center mt-3">
              <a class="btn btn-flat" href="/services/<%= service.service.id %>">Details</a>
            </div>
          <% end %>
        </div>
      </div>
      <script>
        <% if user_signed_in? %>
          window.addEventListener('DOMContentLoaded', (event) => {
            var $wrapper = $('.service-lists');
            $wrapper.find('.service-list-item').sort(function(a, b) {
              return +b.dataset.matching - +a.dataset.matching;
            })
            .appendTo($wrapper);
          });
        <% end %>
      </script>
    <% end %>
  </div>
</div>
<script>
  <% @need_services.each do |service| %>
    let service<%= service.service.id %> = document.getElementById('service-description-' + <%= service.service.id %>);
    if (service<%= service.service.id %>.clientHeight > 128) {
      let expand<%= service.service.id %> = document.createElement("a");
      expand<%= service.service.id %>.innerText = 'Read more';
      expand<%= service.service.id %>.href = '/services/<%= service.service.id %>';
      service<%= service.service.id %>.parentNode.append(expand<%= service.service.id %>);
    }
    while (service<%= service.service.id %>.clientHeight > 128) {
      service<%= service.service.id %>.innerHTML = service<%= service.service.id %>.innerHTML.replace(/\W*\s(\S)*$/, '...');
    }
    let serviceMobile<%= service.service.id %> = document.getElementById('service-description-mobile-' + <%= service.service.id %>);
    if (serviceMobile<%= service.service.id %>.clientHeight > 84) {
      let expandMobile<%= service.service.id %> = document.createElement("a");
      expandMobile<%= service.service.id %>.innerText = 'Read more';
      expandMobile<%= service.service.id %>.href = '/services/<%= service.service.id %>';
      serviceMobile<%= service.service.id %>.parentNode.append(expandMobile<%= service.service.id %>);
    }
    while (serviceMobile<%= service.service.id %>.clientHeight > 84) {
      serviceMobile<%= service.service.id %>.innerHTML = serviceMobile<%= service.service.id %>.innerHTML.replace(/\W*\s(\S)*$/, '...');
    }
  <% end %>
</script>