config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/become-a-practitioner', to: 'pages#become_a_practitioner', as: :become_a_practitioner

  get '/aboutus', to: 'pages#aboutus', as: :aboutus

  get '/faq', to: 'pages#faq', as: :faq

  get '/terms', to: 'pages#terms', as: :terms

  get '/privacy', to: 'pages#privacy', as: :privacy

  get '/cookie', to: 'pages#cookie', as: :cookie

  get '/practitioners/filter', to: 'practitioners#filter', as: :practitioner_filter

  get '/specialties/filter', to: 'specialties#filter', as: :specialty_filter

  get '/session/promo_code', to: 'sessions#promo_code', as: :session_promo_code

  get '/services/more', to: 'services#more'

  get '/user/timezone', to: 'users#timezone', as: :user_timezone

  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  resources :users, only: [:show] do
    resources :practitioners, only: %i[new create]
    resources :conversations, only: [:create]
    resources :user_health_goals, only: [:create]
    resources :referred_users, only: [:create]
    resources :payment_methods, only: [:create]
    resources :user_promos, only: [:create]
  end

  resources :payment_methods, only: %i[update destroy]

  get '/payment', to: 'payments#payment', as: :user_payment

  get '/sessions', to: 'users#booking', as: :user_sessions
  get '/practitioner_sessions', to: 'practitioners#booking', as: :practitioner_sessions
  get '/favourites', to: 'users#favorite', as: :user_favorites
  get '/notifications', to: 'users#notification', as: :user_notifications

  resources :practitioners, only: %i[index show update destroy] do
    resources :practitioner_specialties, only: [:create]
    resources :practitioner_languages, only: [:create]
    resources :practitioner_social_links, only: [:create]
    resources :practitioner_certifications, only: [:create]
    resources :practitioner_memberships, only: [:create]
    resources :favorite_practitioners, only: [:create]
    resources :working_hours, only: [:create]
    resources :practitioner_payments, only: [:new]
  end

  get '/profile', to: 'practitioners#profile', as: :practitioner_profile
  get '/my_services', to: 'practitioners#service', as: :practitioner_services
  get '/discovery_call/:id', to: 'practitioners#discovery_call', as: :practitioner_discovery_call

  resources :practitioner_specialties, only: [:destroy]

  resources :practitioner_languages, only: [:destroy]

  resources :practitioner_social_links, only: [:destroy]

  resources :practitioner_certifications, only: [:destroy]

  resources :practitioner_memberships, only: [:destroy]

  resources :user_health_goals, only: [:destroy]

  resources :favorite_practitioners, only: [:destroy]

  resources :working_hours, only: %i[update destroy]

  resources :languages, only: %i[create destroy]

  resources :specialty_categories, only: %i[create destroy]

  resources :specialties, only: %i[show create destroy]

  resources :health_goals, only: %i[create destroy]

  resources :services, only: %i[create index show update destroy] do
    resources :sessions, only: [:create]
    resources :favorite_services, only: [:create]
    resources :service_health_goals, only: [:create]
    resources :service_promotions, only: [:create]
  end

  resources :service_promotions, only: %i[update destroy]

  resources :service_health_goals, only: [:destroy]

  resources :favorite_services, only: [:destroy]

  resources :sessions, only: %i[show edit update destroy] do
    resources :payments, only: [:new]
    resources :reviews, only: [:create]
  end

  resources :reviews, only: [:destroy]

  resources :notifications, only: %i[update destroy]

  resources :conversations, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :needs, only: [:show]

  resources :events, only: %i[index create show update destroy] do
    resources :event_attendees, only: [:create]
    resources :event_codes, only: [:create]
  end

  resources :event_attendees, only: [:destroy] do
    resources :event_attendee_payments, only: [:new]
  end

  resources :event_codes, only: [:destroy]

  get '/events/:id/codes', to: 'events#codes', as: :event_codes

  post '/events/:id/publish_codes', to: 'events#publish_codes', as: :event_publish_codes

  resources :tax_rates, only: %i[create update destroy]

  get '/blog', to: 'posts#index', as: :posts

  get '/blog/:id', to: 'posts#show', as: :post

  post '/blog', to: 'posts#create'

  get '/blog/:id/edit', to: 'posts#edit', as: :edit_post

  patch '/blog/:id', to: 'posts#update'

  put '/blog/:id', to: 'posts#update'

  delete '/blog/:id', to: 'posts#destroy'

  resources :posts, only: [:new]

  resources :post_categories, only: [:show]

  resources :post_sub_categories, only: [:show]

  resources :post_authors, only: [:show]

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  # post '/background_check/modo_webhooks', to: 'background_check#modo_webhooks'

  post '/background_check/certn_webhooks', to: 'background_check#certn_webhooks'
end

app/views/shared/_blog_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-holistic fixed-top">
  <a class="navbar-brand" href="<%= root_url %>"><%= image_tag('logo', alt: 'The Holistic Panda') %></a>
  <button class="navbar-toggler" type="button" id="open-side">&#9776;</button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Find Holistic Services', services_url, class: 'nav-link find-service' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Welcome, <%= current_user.first_name %> &#9662;</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Admin', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div id="side-nav" class="side-nav">
  <a class="close-side" id="close-side">&times;</a>
  <a href="<%= root_url %>"><%= image_tag('logo', alt: 'The Holistic Panda') %></a>
  <div class="nav-item">
    <%= link_to 'Find Holistic Services', services_url, class: 'nav-link find-service' %>
  </div>
  <% if user_signed_in? %>
    <div class="nav-item">
      <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </div>
  <% else %>
    <div class="nav-item">
      <%= link_to 'Admin', new_user_session_path, class: 'nav-link' %>
    </div>
  <% end %>
</div>

app/views/shared/_filter_form.html.erb
<%= simple_form_for :search, url: services_path, method: "GET", html: { id: 'top-filter-form' } do |f| %>
  <div class="d-flex align-items-center">
    <fieldset class="form-group check_boxes required search_health_goal">
      <% if params[:search] && params[:search][:health_goal] && params[:search][:health_goal].length > 1 %>
        <legend class="btn" id="health-goal-pop">Health Goals (<%= params[:search][:health_goal].reject(&:blank?).count %>)&nbsp;&nbsp;<i class="fas fa-chevron-down"></i></legend>
      <% else %>
        <legend class="btn" id="health-goal-pop">Select Health Goals&nbsp;&nbsp;<i class="fas fa-chevron-down"></i></legend>
      <% end %>
      <div class="health-goal-select-box" id="health-goal-select-box" style="top: 0.5rem !important;">
        <div class="health-goal-choices">
          <% @filtered_services_goals.sort_by(&:name).each do |goal| %>
            <% if params[:search] && params[:search][:health_goal] %>
              <% if params[:search][:health_goal].include?((goal.id).to_s) %>
                <input class="form-check-input check_boxes required hidden" type="checkbox" value="<%= goal.id %>" name="search[health_goal][]" id="search_health_goal_<%= goal.id %>" checked><label class="form-check-label collection_check_boxes health-goal-choice active" for="search_health_goal_<%= goal.id %>"><%= goal.name %></label>
              <% else %>
                <input class="form-check-input check_boxes required hidden" type="checkbox" value="<%= goal.id %>" name="search[health_goal][]" id="search_health_goal_<%= goal.id %>"><label class="form-check-label collection_check_boxes health-goal-choice" for="search_health_goal_<%= goal.id %>"><%= goal.name %></label>
              <% end %>
            <% else %>
              <input class="form-check-input check_boxes required hidden" type="checkbox" value="<%= goal.id %>" name="search[health_goal][]" id="search_health_goal_<%= goal.id %>"><label class="form-check-label collection_check_boxes health-goal-choice" for="search_health_goal_<%= goal.id %>"><%= goal.name %></label>
            <% end %>
          <% end %>
          <input type="hidden" name="search[health_goal][]" value="">
        </div>
        <div class="d-flex justify-content-between pt-3">
          <%= link_to "Reset", services_path, class: 'btn btn-ghost' %>
          <%= f.submit "Apply", class: "btn btn-flat" %>
        </div>
      </div>
    </fieldset>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info notice alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-top">
    <!-- <div style="font-size: 0.75rem; margin-top: -0.5rem; text-align: right; opacity: .7; font-style: italic;">Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> -->
    <div class="footer-columns">
      <h3>About</h3>
      <p><%= link_to 'About us', aboutus_url %></a></p>
      <!-- <p><a href="#">How It Works</a></p> -->
      <p><%= link_to 'FAQ', faq_url %></p>
      <!-- <p><a href="#">Help</a></p> -->
    </div>
    <div class="footer-columns">
      <h3>Community</h3>
      <p><%= link_to 'Events', events_url %></p>
      <p><%= link_to 'Blog', posts_path %></p>
      <% if user_signed_in? %>
        <%= link_to 'Refer a friend', '', data: { toggle: "modal", target: "#referralModal" } %>
      <% else %>
        <%= link_to 'Refer a friend', new_user_session_url %>
      <% end %>
    </div>
    <div class="footer-columns">
      <h3>Practitioner</h3>
      <% if user_signed_in? && current_user.practitioner %>
        <p><%= link_to 'List your practice', practitioner_services_url %></p>
      <% else %>
        <p><%= link_to 'List your practice', become_a_practitioner_url %></p></p>
      <% end %>
      <p><%= link_to 'Get verified now', become_a_practitioner_url %></p></p>
    </div>
    <div class="footer-columns">
      <h3>Connect</h3>
      <div class="footer-socials">
        <a href="https://www.instagram.com/theholisticpanda/" target="_blank"><i class="fab fa-instagram"></i></a>
        <a href="https://www.linkedin.com/company/68969845/" target="_blank"><i class="fab fa-linkedin"></i></a>
        <a href="https://www.youtube.com/channel/UCTGlPkugLBWibO9jU0442-g" target="_blank"><i class="fab fa-youtube"></i></a>
      </div>
      <p><small>For any inquiries, please email us at <a href="mailto:hello@theholisticpanda.com">hello@theholisticpanda.com</a></small></p>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="footer-links">
      <%= link_to 'Terms & conditions', terms_url %> |
      <%= link_to 'Privacy policy', privacy_url %> |
      <%= link_to 'Cookies', cookie_url %>
    </div>
    <div class="footer-copyright">
      © <%= Time.current.year %> TheHolisticPanda, Inc. All rights reserved
    </div>
  </div>
  <div style="font-size: 0.875rem; text-align: center; opacity: .7; font-style: italic; padding-bottom: 1rem;">Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> & <a href="https://www.flaticon.com/authors/flat-icons" title="Flat Icons">Flat Icons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
</div>

app/views/shared/_home_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-holistic fixed-top">
  <a class="navbar-brand" href="<%= root_url %>"><%= image_tag('logo', alt: 'The Holistic Panda') %></a>
  <button class="navbar-toggler" type="button" id="open-side">&#9776;</button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if !current_user.practitioner %>
          <% if current_user.signup_path == '/become-a-practitioner' %>
            <!-- <li class="nav-item">
              <%#= link_to 'Complete practitioner application', new_user_practitioner_path(current_user), class: 'nav-link find-service' %>
            </li> -->
          <% else %>
            <!-- <li class="nav-item">
              <%#= link_to 'Become a practitioner', become_a_practitioner_path, class: 'nav-link find-service' %>
            </li> -->
          <% end %>
        <% end %>
        <li class="nav-item btn-group">
          <a class="dropdown-toggle nav-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell"></i>
            <span class="unread-count" id="unread-count">
              <%= @notifications.length if @notifications.present? %>
            </span>
          </a>
          <div class="dropdown-menu notification-drop" aria-labelledby="dropdownMenu1">
            <% if @notifications.present? %>
              <% @notifications.first(10).each do |notification| %>
                <%= link_to notification.actor.full_name + " " + notification.action, notification_path(notification), method: :patch || :put, class: 'dropdown-item' %>
              <% end %>
            <% end %>
            <%= link_to 'See all', user_notifications_path, class: 'dropdown-item text-center all' %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Welcome, <%= current_user.first_name %> &#9662;</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.conversations.present? %>
              <%= link_to 'Messages', conversation_path(current_user.last_conversation), class: 'dropdown-item' %>
            <% end %>
            <% if current_user.practitioner && current_user.practitioner.checked? %>
              <%= link_to 'Sessions as client', user_sessions_path, class: 'dropdown-item' %>
            <% else %>
              <%= link_to 'Sessions', user_sessions_path, class: 'dropdown-item' %>
            <% end %>
            <%= link_to 'Favourites', user_favorites_path, class: 'dropdown-item' %>
            <%= link_to 'Refer a friend', '', data: { toggle: "modal", target: "#referralModal" }, class: 'dropdown-item' %>
            <hr>
            <% if current_user.practitioner %>
              <%= link_to 'Profile', practitioner_profile_path, class: 'dropdown-item' %>
              <% if current_user.practitioner.checked? %>
                <%= link_to 'Sessions as practitioner', practitioner_sessions_path, class: 'dropdown-item' %>
                <%= link_to 'Services', practitioner_services_path, class: 'dropdown-item' %>
                <%= link_to 'View my page', practitioner_path(current_user.practitioner), class: 'dropdown-item' %>
                <% if current_user.practitioner.stripe_account_id %>
                  <%= simple_form_for([current_user.practitioner], html: { id: :payouts_form }) do |f| %>
                    <%= f.button :submit, "Payouts dashboard", class: 'dropdown-item' %>
                  <% end %>
                <% end %>
              <% end %>
            <% else %>
              <%= link_to 'Profile', user_path(current_user), class: 'dropdown-item' %>
            <% end %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <!-- <li class="nav-item">
          <%#= link_to 'Become a practitioner', become_a_practitioner_path, class: 'nav-link find-service' %>
        </li> -->
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div id="side-nav" class="side-nav">
  <a class="close-side" id="close-side">&times;</a>
  <a href="<%= root_url %>"><%= image_tag('logo', alt: 'The Holistic Panda') %></a>
  <% if user_signed_in? %>
    <% if !current_user.practitioner %>
      <% if current_user.signup_path == '/become-a-practitioner' %>
        <!-- <div class="nav-item">
          <%#= link_to 'Complete practitioner application', new_user_practitioner_path(current_user), class: 'nav-link find-service' %>
        </div> -->
      <% else %>
        <!-- <div class="nav-item">
          <%#= link_to 'Become a practitioner', become_a_practitioner_path, class: 'nav-link find-service' %>
        </div> -->
      <% end %>
    <% end %>
    <div class="nav-item">
      <div class="d-flex align-items-center">
        <%= link_to 'Notifications', user_notifications_path, class: 'nav-link' %>
        <span class="unread-count" id="unread-count" style="font-size: 1.2rem; margin-left: -1rem;">
          <%= @notifications.length if @notifications.present? %>
        </span>
      </div>
    </div>
    <% if current_user.conversations.present? %>
      <div class="nav-item">
        <%= link_to 'Messages', conversation_path(current_user.last_conversation), class: 'nav-link' %>
      </div>
    <% end %>
    <% if current_user.practitioner && current_user.practitioner.checked? %>
      <div class="nav-item">
        <%= link_to 'Sessions as client', user_sessions_path, class: 'nav-link' %>
      </div>
    <% else %>
      <div class="nav-item">
        <%= link_to 'Sessions', user_sessions_path, class: 'nav-link' %>
      </div>
    <% end %>
    <div class="nav-item">
      <%= link_to 'Favourites', user_favorites_path, class: 'nav-link' %>
    </div>
    <div class="nav-item">
      <%= link_to 'Refer a friend', '', data: { toggle: "modal", target: "#referralModal" }, class: 'nav-link' %>
    </div>
    <% if current_user.practitioner %>
      <div class="nav-item">
        <%= link_to 'Profile', practitioner_profile_path, class: 'nav-link' %>
      </div>
      <% if current_user.practitioner.checked? %>
        <div class="nav-item">
          <%= link_to 'Sessions as practitioner', practitioner_sessions_path, class: 'nav-link' %>
        </div>
        <div class="nav-item">
          <%= link_to 'Services', practitioner_services_path, class: 'nav-link' %>
        </div>
        <div class="nav-item">
          <%= link_to 'View my page', practitioner_path(current_user.practitioner), class: 'nav-link' %>
        </div>
        <% if current_user.practitioner.stripe_account_id %>
          <div class="nav-item">
            <%= simple_form_for([current_user.practitioner], html: { id: :payouts_form_mobile }) do |f| %>
              <%= f.button :submit, "Payouts dashboard", class: 'nav-link' %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="nav-item">
        <%= link_to 'Profile', user_path(current_user), class: 'nav-link' %>
      </div>
    <% end %>
    <div class="nav-item">
      <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
    </div>
  <% else %>
    <!-- <div class="nav-item">
      <%#= link_to 'Become a practitioner', become_a_practitioner_path, class: 'nav-link find-service' %>
    </div> -->
    <div class="nav-item">
      <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
    </div>
    <div class="nav-item">
      <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-holistic fixed-top">
  <a class="navbar-brand" href="<%= root_url %>"><%= image_tag('logo', alt: 'The Holistic Panda') %></a>
  <button class="navbar-toggler" type="button" id="open-side">&#9776;</button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Find Holistic Services', services_url, class: 'nav-link find-service' %>
        </li>
        <li class="nav-item btn-group">
          <a class="dropdown-toggle nav-link" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell"></i>
            <span class="unread-count" id="unread-count">
              <%= @notifications.length if @notifications.present? %>
            </span>
          </a>
          <div class="dropdown-menu notification-drop" aria-labelledby="dropdownMenu1">
            <% if @notifications.present? %>
              <% @notifications.first(10).each do |notification| %>
                <%= link_to notification.actor.full_name + " " + notification.action, notification_url(notification), method: :patch || :put, class: 'dropdown-item' %>
              <% end %>
            <% end %>
            <%= link_to 'See all', user_notifications_url, class: 'dropdown-item text-center all' %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Welcome, <%= current_user.first_name %> &#9662;</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.conversations.present? %>
              <%= link_to 'Messages', conversation_url(current_user.last_conversation), class: 'dropdown-item' %>
            <% end %>
            <% if current_user.practitioner && current_user.practitioner.checked? %>
              <%= link_to 'Sessions as client', user_sessions_url, class: 'dropdown-item' %>
            <% else %>
              <%= link_to 'Sessions', user_sessions_url, class: 'dropdown-item' %>
            <% end %>
            <%= link_to 'Favourites', user_favorites_url, class: 'dropdown-item' %>
            <%= link_to 'Refer a friend', '', data: { toggle: "modal", target: "#referralModal" }, class: 'dropdown-item' %>
            <hr>
            <% if current_user.practitioner %>
              <%= link_to 'Profile', practitioner_profile_url, class: 'dropdown-item' %>
              <% if current_user.practitioner.checked? %>
                <%= link_to 'Sessions as practitioner', practitioner_sessions_url, class: 'dropdown-item' %>
                <%= link_to 'Services', practitioner_services_url, class: 'dropdown-item' %>
                <%= link_to 'View my page', practitioner_url(current_user.practitioner), class: 'dropdown-item' %>
                <% if current_user.practitioner.stripe_account_id %>
                  <%= simple_form_for([current_user.practitioner], html: { id: :payouts_form }) do |f| %>
                    <%= f.button :submit, "Payouts dashboard", class: 'dropdown-item' %>
                  <% end %>
                <% end %>
              <% end %>
            <% else %>
              <%= link_to 'Profile', user_url(current_user), class: 'dropdown-item' %>
            <% end %>
            <%= link_to 'Log out', destroy_user_session_url, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Find Holistic Services', services_url, class: 'nav-link find-service' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_url, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', new_user_session_url, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div id="side-nav" class="side-nav">
  <a class="close-side" id="close-side">&times;</a>
  <a href="<%= root_url %>"><%= image_tag('logo', alt: 'The Holistic Panda') %></a>
  <% if user_signed_in? %>
    <div class="nav-item">
      <%= link_to 'Find Holistic Services', services_url, class: 'nav-link find-service' %>
    </div>
    <div class="nav-item">
      <div class="d-flex align-items-center">
        <%= link_to 'Notifications', user_notifications_url, class: 'nav-link' %>
        <span class="unread-count" id="unread-count" style="font-size: 1.2rem; margin-left: -1rem;">
          <%= @notifications.length if @notifications.present? %>
        </span>
      </div>
    </div>
    <% if current_user.conversations.present? %>
      <div class="nav-item">
        <%= link_to 'Messages', conversation_url(current_user.last_conversation), class: 'nav-link' %>
      </div>
    <% end %>
    <% if current_user.practitioner && current_user.practitioner.checked? %>
      <div class="nav-item">
        <%= link_to 'Sessions as client', user_sessions_url, class: 'nav-link' %>
      </div>
    <% else %>
      <div class="nav-item">
        <%= link_to 'Sessions', user_sessions_url, class: 'nav-link' %>
      </div>
    <% end %>
    <div class="nav-item">
      <%= link_to 'Favourites', user_favorites_url, class: 'nav-link' %>
    </div>
    <div class="nav-item">
      <%= link_to 'Refer a friend', '', data: { toggle: "modal", target: "#referralModal" }, class: 'nav-link' %>
    </div>
    <% if current_user.practitioner %>
      <div class="nav-item">
        <%= link_to 'Profile', practitioner_profile_url, class: 'nav-link' %>
      </div>
      <% if current_user.practitioner.checked? %>
        <div class="nav-item">
          <%= link_to 'Sessions as practitioner', practitioner_sessions_url, class: 'nav-link' %>
        </div>
        <div class="nav-item">
          <%= link_to 'Services', practitioner_services_url, class: 'nav-link' %>
        </div>
        <div class="nav-item">
          <%= link_to 'View my page', practitioner_url(current_user.practitioner), class: 'nav-link' %>
        </div>
        <% if current_user.practitioner.stripe_account_id %>
          <div class="nav-item">
            <%= simple_form_for([current_user.practitioner], html: { id: :payouts_form_mobile }) do |f| %>
              <%= f.button :submit, "Payouts dashboard", class: 'nav-link' %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="nav-item">
        <%= link_to 'Profile', user_url(current_user), class: 'nav-link' %>
      </div>
    <% end %>
    <div class="nav-item">
      <%= link_to 'Log out', destroy_user_session_url, method: :delete, class: 'nav-link' %>
    </div>
  <% else %>
    <div class="nav-item">
      <%= link_to 'Find Holistic Services', services_url, class: 'nav-link find-service' %>
    </div>
    <div class="nav-item">
      <%= link_to 'Sign up', new_user_registration_url, class: 'nav-link' %>
    </div>
    <div class="nav-item">
      <%= link_to 'Login', new_user_session_url, class: 'nav-link' %>
    </div>
  <% end %>
</div>

app/views/shared/_timezone.html.erb
<script>
  document.addEventListener('DOMContentLoaded', () => {
    <% if user_signed_in? %>
      if (moment.tz.guess() != '<%= current_user.timezone %>') {
        $.ajax({
          url: '/user/timezone',
          data: {timezone: moment.tz.guess()},
          success: function(data){
            location.reload();
          }
        });
      }
    <% end %>
  });
</script>